=== Sliweczkowa/MyLittleCookBook/cookbookStructure.dtd
<!ELEMENT cookbook (pageInfo,pageContent)>
<!ELEMENT pageInfo (authorName, authorGitHub, lastModificationDate)>
    <!ELEMENT authorName (#PCDATA)>
    <!ELEMENT authorGitHub (#PCDATA)>
    <!ELEMENT lastModificationDate (#PCDATA)>
<!ELEMENT pageContent (recipes, ingredients)>
    <!ELEMENT recipes (recipe*)>
        <!ELEMENT recipe (dishInfo, dishChangeable?, dishIngredients?)>
        <!ATTLIST recipe recipeID CDATA #REQUIRED>
            <!ELEMENT dishInfo (dishName, dishType, prepTime, bakingTime, bakingTemp, dishQuantity, dishSource)>
                <!ELEMENT dishName (#PCDATA)>
                <!ELEMENT dishType (#PCDATA)>
                <!ELEMENT prepTime (#PCDATA)>
                    <!ATTLIST prepTime unit (min|h) #REQUIRED>
                <!ELEMENT bakingTime (#PCDATA)>
                    <!ATTLIST bakingTime unit (min|h) #REQUIRED>
                <!ELEMENT bakingTemp (#PCDATA)>
                    <!ATTLIST bakingTemp unit CDATA #REQUIRED>
                <!ELEMENT dishQuantity (#PCDATA)>
                <!ELEMENT dishSource (#PCDATA)>
            <!ELEMENT dishChangeable (lastDateMade?)>
                <!ELEMENT lastDateMade (#PCDATA)>
            <!ELEMENT dishIngredients (dishIngredient*)>
                <!ELEMENT dishIngredient (dishIngredientName, dishIngredientQuantity)>
                <!ATTLIST dishIngredient dishIngredientID CDATA #REQUIRED>
                    <!ELEMENT dishIngredientName (#PCDATA)>
                    <!ELEMENT dishIngredientQuantity (#PCDATA)>
                        <!ATTLIST dishIngredientQuantity unit (g|kg|ml|l|teaspoon|spoon|ea) #REQUIRED>
    <!ELEMENT ingredients (ingredient*)>
    <!ELEMENT ingredient (ingredientName, ingredientType, ingredientCalories?, ingredientCostPerQuantity*)>
        <!ATTLIST ingredient ingredientID CDATA #REQUIRED>
        <!ATTLIST ingredient isAllergen (yes|no) #REQUIRED>
        <!ELEMENT ingredientName (#PCDATA)>
        <!ELEMENT ingredientType (#PCDATA)>
        <!ELEMENT ingredientCalories (#PCDATA)>
        <!ELEMENT ingredientCostPerQuantity (ingredientCost, ingredientQuantity)>
            <!ELEMENT ingredientCost (#PCDATA)>
                <!ATTLIST ingredientCost unit (zl|eur) #REQUIRED>
            <!ELEMENT ingredientQuantity (#PCDATA)>
                <!ATTLIST ingredientQuantity unit (g|kg|ml|l|teaspoon|spoon|ea) #REQUIRED>

=== Sliweczkowa/MyLittleCookBook/cookbook.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Simple XML project created for learning purposes -->

<?xml-stylesheet type="text/css" href="cookbookStyle.css"?>
<?xml-stylesheet type="text/xsl" href="cookbookStructure.xsl"?>
<!--<!DOCTYPE cookbook SYSTEM "cookbookStructure.dtd">-->

<cookbook>
    <pageInfo>
        <authorName>Wiktoria Śliwińska</authorName>
        <authorGitHub>@Sliweczkowa</authorGitHub>
        <lastModificationDate>2023-09-05</lastModificationDate>
    </pageInfo>

    <pageContent>
        <recipes>
            <recipe recipeID="r00001">
                <dishInfo>
                    <dishName>Snickerdoodles</dishName>
                    <dishType>vegetarian</dishType>
                    <prepTime unit="h">2</prepTime>
                    <bakingTime unit="min">15</bakingTime>
                    <bakingTemp unit="°C">180</bakingTemp>
                    <dishQuantity>30</dishQuantity>
                    <dishSource>https://mojewypieki.com/przepis/snickerdoodles</dishSource>
                </dishInfo>

                <dishChangeable>
                    <lastDateMade>2023-08-31</lastDateMade>
                    <!-- <dishCost unit="zl"></dishCost> -->
                </dishChangeable>

                <dishIngredients>
                    <dishIngredient dishIngredientID="i00001">
                        <dishIngredientName>Wheat flour</dishIngredientName>
                        <dishIngredientQuantity unit="g">250</dishIngredientQuantity>
                    </dishIngredient>
                    <dishIngredient dishIngredientID="i00002">
                        <dishIngredientName>Nutmeg</dishIngredientName>
                        <dishIngredientQuantity unit="teaspoon">0.5</dishIngredientQuantity>
                    </dishIngredient>
                    <dishIngredient dishIngredientID="i00003">
                        <dishIngredientName>Baking powder</dishIngredientName>
                        <dishIngredientQuantity unit="teaspoon">0.75</dishIngredientQuantity>
                    </dishIngredient>
                    <dishIngredient dishIngredientID="i00004">
                        <dishIngredientName>Salt</dishIngredientName>
                        <dishIngredientQuantity unit="teaspoon">0.5</dishIngredientQuantity>
                    </dishIngredient>
                    <dishIngredient dishIngredientID="i00005">
                        <dishIngredientName>Butter</dishIngredientName>
                        <dishIngredientQuantity unit="g">125</dishIngredientQuantity>
                    </dishIngredient>
                    <dishIngredient dishIngredientID="i00006">
                        <dishIngredientName>Sugar</dishIngredientName>
                        <dishIngredientQuantity unit="g">100</dishIngredientQuantity>
                    </dishIngredient>
                    <dishIngredient dishIngredientID="i00007">
                        <dishIngredientName>Egg</dishIngredientName>
                        <dishIngredientQuantity unit="ea">1</dishIngredientQuantity>
                    </dishIngredient>
                    <dishIngredient dishIngredientID="i00008">
                        <dishIngredientName>Vanilla extract</dishIngredientName>
                        <dishIngredientQuantity unit="teaspoon">1</dishIngredientQuantity>
                    </dishIngredient>
                    <dishIngredient dishIngredientID="i00009">
                        <dishIngredientName>Cinnamon</dishIngredientName>
                        <dishIngredientQuantity unit="spoon">1</dishIngredientQuantity>
                    </dishIngredient>
                </dishIngredients>
            </recipe>

            <recipe recipeID="r00002">
                <dishInfo>
                    <dishName>Brownie</dishName>
                    <dishType>vegetarian</dishType>
                    <!-- carnivore/vegetarian/vegan -->
                    <prepTime unit="h">2</prepTime>
                    <bakingTime unit="min">30</bakingTime>
                    <bakingTemp unit="°C">160</bakingTemp>
                    <dishQuantity>20</dishQuantity>
                    <dishSource>https://www.kwestiasmaku.com/desery/ciasta/czekoladowe_brownie/przepis.html</dishSource>
                </dishInfo>

                <dishIngredients>
                    <dishIngredient dishIngredientID="i00005">
                        <dishIngredientName>Butter</dishIngredientName>
                        <dishIngredientQuantity unit="g">200</dishIngredientQuantity>
                    </dishIngredient>
                    <dishIngredient dishIngredientID="i00010">
                        <dishIngredientName>Dark chocolate</dishIngredientName>
                        <dishIngredientQuantity unit="g">200</dishIngredientQuantity>
                    </dishIngredient>
                    <dishIngredient dishIngredientID="i00007">
                        <dishIngredientName>Egg</dishIngredientName>
                        <dishIngredientQuantity unit="ea">3</dishIngredientQuantity>
                    </dishIngredient>
                    <dishIngredient dishIngredientID="i00006">
                        <dishIngredientName>Sugar</dishIngredientName>
                        <dishIngredientQuantity unit="g">250</dishIngredientQuantity>
                    </dishIngredient>
                    <dishIngredient dishIngredientID="i00001">
                        <dishIngredientName>Wheat flour</dishIngredientName>
                        <dishIngredientQuantity unit="g">135</dishIngredientQuantity>
                    </dishIngredient>
                    <dishIngredient dishIngredientID="i00004">
                        <dishIngredientName>Salt</dishIngredientName>
                        <dishIngredientQuantity unit="teaspoon">0.1</dishIngredientQuantity>
                    </dishIngredient>
                </dishIngredients>
            </recipe>

            <recipe recipeID="r00003">
                <dishInfo>
                    <dishName>Cotton Japanese Cheesecake</dishName>
                    <dishType>vegetarian</dishType>
                    <prepTime unit="h">2</prepTime>
                    <bakingTime unit="min">25</bakingTime>
                    <bakingTemp unit="°C">140</bakingTemp>
                    <dishQuantity>6</dishQuantity>
                    <dishSource>https://www.youtube.com/watch?v=DueW3q1AFoM&amp;t=672s</dishSource>
                </dishInfo>

                <dishChangeable>
                    <lastDateMade>2023-07-03</lastDateMade>
                </dishChangeable>

                <dishIngredients>
                    <dishIngredient dishIngredientID="i00011">
                        <dishIngredientName>Biscuit</dishIngredientName>
                        <dishIngredientQuantity unit="ea">6</dishIngredientQuantity>
                    </dishIngredient>
                    <dishIngredient dishIngredientID="i00005">
                        <dishIngredientName>Butter</dishIngredientName>
                        <dishIngredientQuantity unit="g">70</dishIngredientQuantity>
                    </dishIngredient>
                    <dishIngredient dishIngredientID="i00012">
                        <dishIngredientName>Philadelphia</dishIngredientName>
                        <dishIngredientQuantity unit="g">110</dishIngredientQuantity>
                    </dishIngredient>
                    <dishIngredient dishIngredientID="i00013">
                        <dishIngredientName>Milk</dishIngredientName>
                        <dishIngredientQuantity unit="ml">75</dishIngredientQuantity>
                    </dishIngredient>
                    <dishIngredient dishIngredientID="i00007">
                        <dishIngredientName>Egg</dishIngredientName>
                        <dishIngredientQuantity unit="ea">3</dishIngredientQuantity>
                    </dishIngredient>
                    <dishIngredient dishIngredientID="i00001">
                        <dishIngredientName>Wheat flour</dishIngredientName>
                        <dishIngredientQuantity unit="g">30</dishIngredientQuantity>
                    </dishIngredient>
                    <dishIngredient dishIngredientID="i00014">
                        <dishIngredientName>Potato starch</dishIngredientName>
                        <dishIngredientQuantity unit="g">20</dishIngredientQuantity>
                    </dishIngredient>
                    <dishIngredient dishIngredientID="i00006">
                        <dishIngredientName>Sugar</dishIngredientName>
                        <dishIngredientQuantity unit="g">60</dishIngredientQuantity>
                    </dishIngredient>
                    <dishIngredient dishIngredientID="i00008">
                        <dishIngredientName>Vanilla extract</dishIngredientName>
                        <dishIngredientQuantity unit="teaspoon">1</dishIngredientQuantity>
                    </dishIngredient>
                </dishIngredients>
            </recipe>
        </recipes>

        <ingredients>
            <ingredient ingredientID="i00001" isAllergen="yes">
                <ingredientName>Wheat flour</ingredientName>
                <ingredientType>vegan</ingredientType>
                <ingredientCalories>350</ingredientCalories>
                <ingredientCostPerQuantity>
                    <ingredientCost unit="zl">3.48</ingredientCost>
                    <ingredientQuantity unit="kg">1</ingredientQuantity>
                </ingredientCostPerQuantity>
            </ingredient>
            <ingredient ingredientID="i00002" isAllergen="no">
                <ingredientName>Nutmeg</ingredientName>
                <ingredientType>vegan</ingredientType>
                <ingredientCalories>52.5</ingredientCalories>
                <ingredientCostPerQuantity>
                    <ingredientCost unit="zl">1.48</ingredientCost>
